name: hackethos4u
description: "Hackethos4u - Learn Cybersecurity and Ethical Hacking"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase (latest, matching firebase-bom 33.7.0)
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.2
  firebase_analytics: ^12.0.2
  firebase_storage: ^13.0.2

  # Authentication
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.0

  # Media & Files
  image_picker: ^1.1.2
  video_player: ^2.9.2
  chewie: ^1.8.1
  file_picker: ^10.3.3
  image: ^4.2.0

  # UI & Navigation
  provider: ^6.1.2
  get: ^4.6.6

  # Network & Storage
  http: ^1.2.2
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.3

  # JSON & Serialization
  json_annotation: ^4.9.0

  # UI Components
  percent_indicator: ^4.2.3
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^19.4.2
  url_launcher: ^6.3.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  lottie: ^3.3.0

  # PDF & Documents
  pdf: ^3.11.0
  printing: ^5.14.0
  open_file: ^3.3.4

  # Web & Connectivity
  webview_flutter: ^4.9.0
  connectivity_plus: ^7.0.0

  # Validation
  email_validator: ^3.0.0

  # Utilities
  intl: ^0.20.2
  share_plus: ^12.0.0
  permission_handler: ^12.0.1

  # Security
  wakelock_plus: ^1.2.8
  screen_protector: ^1.3.3

  # Payment
  razorpay_flutter: ^1.3.8

  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/banner/
    - assets/courses/
    - assets/checklist_icon.png
    - assets/default_pp.png
    - assets/empty_image.png
    - assets/garland.svg
    - assets/hackethos4u_logo.png
    - assets/medail.svg
    - assets/swirls.svg
    - assets/swirls1.svg
    - assets/swirls2.svg
    - assets/swirls3.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Light.ttf
          weight: 300
